# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sale_pb2 as sale__pb2


class CalculatorSaleStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSale = channel.unary_unary(
        '/CalculatorSale/GetSale',
        request_serializer=sale__pb2.Cost.SerializeToString,
        response_deserializer=sale__pb2.Cost.FromString,
        )


class CalculatorSaleServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSale(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculatorSaleServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSale': grpc.unary_unary_rpc_method_handler(
          servicer.GetSale,
          request_deserializer=sale__pb2.Cost.FromString,
          response_serializer=sale__pb2.Cost.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CalculatorSale', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
