# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sale.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sale.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\nsale.proto\"\x14\n\x04\x43ost\x12\x0c\n\x04\x63ost\x18\x01 \x01(\x02\x32+\n\x0e\x43\x61lculatorSale\x12\x19\n\x07GetSale\x12\x05.Cost\x1a\x05.Cost\"\x00\x62\x06proto3')
)




_COST = _descriptor.Descriptor(
  name='Cost',
  full_name='Cost',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cost', full_name='Cost.cost', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=34,
)

DESCRIPTOR.message_types_by_name['Cost'] = _COST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Cost = _reflection.GeneratedProtocolMessageType('Cost', (_message.Message,), dict(
  DESCRIPTOR = _COST,
  __module__ = 'sale_pb2'
  # @@protoc_insertion_point(class_scope:Cost)
  ))
_sym_db.RegisterMessage(Cost)



_CALCULATORSALE = _descriptor.ServiceDescriptor(
  name='CalculatorSale',
  full_name='CalculatorSale',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=36,
  serialized_end=79,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSale',
    full_name='CalculatorSale.GetSale',
    index=0,
    containing_service=None,
    input_type=_COST,
    output_type=_COST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CALCULATORSALE)

DESCRIPTOR.services_by_name['CalculatorSale'] = _CALCULATORSALE

# @@protoc_insertion_point(module_scope)
